from .schemas import CreateUser, LoginUser,CustomerModel
from sqlmodel import select,delete
from sqlmodel.ext.asyncio.session import AsyncSession
from db.models import User
from fastapi.exceptions import HTTPException
from fastapi import status
from fastapi.responses import JSONResponse
from .utils import generate_pass_hash,verify_password,create_access_token
from utils.errors import UserAlreadyExists,UserNotFound
from datetime import timedelta

from utils.errors import InvalidCredentials

REFRESH_TOKEN_EXPIRY = 2


class AuthService:


    async def user_exists(
            self,
            email: str,
            session: AsyncSession
    ):
        user = await self.get_user_by_email(email,session)

        return True if user is not None else False
    
    
    async def get_user_by_email(
        self,
        email: str,
        session: AsyncSession
    ):
        query = select(User).where(User.email == email)
        result = await session.exec(query)
        
        return result.first()
    

    async def create_customer(
        self,
        user: CreateUser,
        session: AsyncSession
    ):
        user_exists = await self.get_user_by_email(user.email, session)
        if user_exists:
            raise UserAlreadyExists(f"User with email {user.email} already exists")

        hashed_password = generate_pass_hash(user.password)

        new_user = User(**user.model_dump())
        new_user.password = hashed_password

        session.add(new_user)
        await session.commit()
        await session.refresh(new_user)  # Refresh to get the ID and other autogenerated fields

        return new_user
    
    async def create_vendor(
        self,
        user: CreateUser,
        session: AsyncSession
    ):
        user_exists = await self.get_user_by_email(user.email, session)
        if user_exists:
            raise UserAlreadyExists(f"User with email {user.email} already exists")

        hashed_password = generate_pass_hash(user.password)

        new_user = User(**user.model_dump())
        new_user.password = hashed_password
        new_user.role = 'vendor'


        session.add(new_user)
        await session.commit()
        await session.refresh(new_user)  # Refresh to get the ID and other autogenerated fields

        return new_user
    

    async def get_all_customers(
        self,
        session: AsyncSession     
    ):
        query = select(User).where(User.role == 'customer')
        result = await session.exec(query)
        return result.all()
    
    async def get_all_vendors(
        self,
        session: AsyncSession     
    ):
        query = select(User).where(User.role == 'vendor')
        result = await session.exec(query)
        return result.all()
       


    async def update_user(
        self,
        user:User,
        user_data: dict,
        session: AsyncSession
    ):
        for k,v in user_data.items():
            setattr(user,k,v)
        
        await session.commit()

        return user    
    

    async def remove_customer_by_email(
        self,
        email: str    ,
        session: AsyncSession
    ):
        user_det = await self.get_user_by_email(email,session)

        if user_det:
            
            statement = delete(User).where(User.email == user_det.email)
        
            result = await session.exec(statement=statement)

            await session.commit()
            return True
        return False