"""Solved the coupon model issue

Revision ID: 05ba7acfbbb1
Revises: 1e46f2b16f0b
Create Date: 2026-02-01 08:01:28.149690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ba7acfbbb1'
down_revision: Union[str, Sequence[str], None] = '1e46f2b16f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
