"""user product many to many solved error

Revision ID: 597affc42e43
Revises: 9a2f198352ff
Create Date: 2026-02-01 01:11:42.210221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597affc42e43'
down_revision: Union[str, Sequence[str], None] = '9a2f198352ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('imageUrl', sa.ARRAY(sa.VARCHAR()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'imageUrl')
    # ### end Alembic commands ###
