"""Invoice entity added

Revision ID: 6ab56dbdf8e4
Revises: 05ba7acfbbb1
Create Date: 2026-02-01 09:00:20.493821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab56dbdf8e4'
down_revision: Union[str, Sequence[str], None] = '05ba7acfbbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
