"""Invoice entity added

Revision ID: e9646d7c3a8b
Revises: 6ab56dbdf8e4
Create Date: 2026-02-01 09:22:36.165247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9646d7c3a8b'
down_revision: Union[str, Sequence[str], None] = '6ab56dbdf8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
